# Generated by Django 4.2.6 on 2024-03-02 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0005_alter_posts_user_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="user_info",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Userinfo",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
