# Generated by Django 4.2.6 on 2024-03-02 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0006_alter_posts_user_info"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="followers",
            new_name="follower",
        ),
        migrations.AddField(
            model_name="follow",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userfollow",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
