# Generated by Django 4.2.6 on 2024-03-02 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0007_rename_followers_follow_follower_follow_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="follower",
        ),
        migrations.AddField(
            model_name="follow",
            name="follower",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
