# Generated by Django 4.2.6 on 2024-03-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0011_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="dislikes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="posts",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Likes",
        ),
    ]
