# Generated by Django 4.2.6 on 2024-03-03 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0012_posts_dislikes_posts_likes_delete_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="dislikes",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userdislike",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="likes",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userlike",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
