# Generated by Django 4.2.6 on 2024-03-06 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0016_likes_liked_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likes",
            name="liked_user",
            field=models.ManyToManyField(
                default=None,
                null=True,
                related_name="userlikedPosts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
