# Generated by Django 4.2.6 on 2024-03-07 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0017_alter_likes_liked_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="likes",
            name="liked_user",
        ),
        migrations.RemoveField(
            model_name="posts",
            name="user_info",
        ),
    ]
