# Generated by Django 4.2.6 on 2024-03-07 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0018_remove_likes_liked_user_remove_posts_user_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="disliked_users",
            field=models.ManyToManyField(
                default=None,
                null=True,
                related_name="userDisliked",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
