# Generated by Django 4.2.6 on 2024-03-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0019_posts_disliked_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.CharField(default=None, max_length=20000, null=True),
                ),
                (
                    "post",
                    models.ManyToManyField(
                        related_name="postComment", to="media.posts"
                    ),
                ),
            ],
        ),
    ]
