# Generated by Django 4.2.6 on 2024-03-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0022_remove_comment_post_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="times_loggin_in",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
