# Generated by Django 4.2.6 on 2024-04-06 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0023_user_times_loggin_in"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_image",
                    models.CharField(default=None, max_length=10000000, null=True),
                ),
                (
                    "bio",
                    models.TextField(default=None, max_length=10000000000, null=True),
                ),
                (
                    "first_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profileFirstname",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profileLastName",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profileUsername",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
