# Generated by Django 4.2.6 on 2024-04-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0025_alter_profile_first_name_alter_profile_last_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(default=None, max_length=10000000000, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.CharField(default=None, max_length=10000000, null=True),
        ),
    ]
