# Generated by Django 4.2.6 on 2024-04-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0026_delete_profile_user_bio_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(null=True, upload_to="uploads/"),
        ),
    ]
