# Generated by Django 4.2.6 on 2024-04-07 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0028_remove_follow_user_being_followed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="user_being_followed",
        ),
        migrations.RemoveField(
            model_name="follow",
            name="user_that_is_following",
        ),
        migrations.AddField(
            model_name="follow",
            name="user_being_followed",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="follow",
            name="user_that_is_following",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userfollow",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
