# Generated by Django 4.2.6 on 2024-04-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0029_remove_follow_user_being_followed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="user_that_is_following",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="follow",
            old_name="user_being_followed",
            new_name="userf",
        ),
    ]
