# Generated by Django 4.2.6 on 2024-04-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0030_rename_user_that_is_following_follow_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
