# Generated by Django 4.2.6 on 2024-04-16 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0031_alter_user_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="disliked_users",
        ),
        migrations.AddField(
            model_name="posts",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userPost",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
